// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Writer_addWriterStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Writer_addWriterStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202204131421175_Writer_addWriterStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
